# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    groups:
      actions-deps:
        patterns:
          - "*"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for Go Modules
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    groups:
      actions-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  # Maintain dependencies for npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/validator/imported" # Location of package manifests
    groups:
      actions-deps:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
